; CutiSmart Attendance Firmware
; Target: ESP32-2432S028R (Cheap Yellow Display, revisi USB-C)
; Fitur: rotating QR + iBeacon advertise + WiFi enroll captive portal

[platformio]
default_envs = cyd

[env:cyd]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

board_build.f_flash = 40000000L
board_build.flash_mode = dio
board_build.partitions = huge_app.csv

build_flags =
  ; TFT_eSPI konfigurasi untuk CYD (ILI9341 240x320 + backlight GPIO21)
  -DUSER_SETUP_LOADED=1
  -DILI9341_2_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=2
  -DTFT_RST=-1
  -DTFT_BL=21
  -DTFT_BACKLIGHT_ON=HIGH
  -DTFT_INVERSION_ON=1
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_FONT4=1
  -DLOAD_FONT6=1
  -DSMOOTH_FONT=1
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=20000000
  ; NimBLE mode (hemat RAM vs BLE stack default)
  -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
  ; Firmware identity
  -DFIRMWARE_VERSION="\"0.1.0\""
  -DAP_SSID="\"CutiSmart-Setup\""

lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  tzapu/WiFiManager@^2.0.17
  bblanchon/ArduinoJson@^7.2.1
  ricmoo/QRCode@^0.0.1
  h2zero/NimBLE-Arduino@^1.4.2

monitor_filters = esp32_exception_decoder, colorize
